name: Reusable build
on:
  workflow_call:
    inputs:
      artifact:
        default: release-artifact
        required: false
        type: string
    outputs:
      git-sha: 
        value: ${{ jobs.build.outputs.git-sha }}
      git-branch:
        value: ${{ jobs.build.outputs.git-branch }}
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      git-sha: ${{ steps.vars.outputs.sha }}
      git-branch: ${{ steps.vars.outputs.branch }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Cache local maven repository
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Environment detector
        id: vars
        shell: bash
        run: |
          echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT
      - run: ./gradlew assemble
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifact }}
          path: build/distributions
